export default {
  EMPTY: '',
  DEFAULT_USER: 'vuongluu',
  DEFAULT_PASSWORD: '!23456Abc',
  DEFAULT_COLOR: '#1abc9c',
  DEFAULT_SERVER: 'http://heart-warming-analy.000webhostapp.com/public',
  DEFAULT_SYNC_URI: '/api/v1/sync',
  DEFAULT_BACKUP_URI: '/api/v1/backup',
  DEFAULT_AUTH_URI: '/api/v1/auth',
  DEFAULT_SETTING_URI: '/api/v1/settings',
  VALIDATE: {
  	username_required: 'Tên đăng nhập là bắt buộc',
  	password_required: 'Mật khẩu là bắt buộc',
  	invalid_account: 'Tài khoản hoặc mật khẩu không chính xác'
  },
  REIGSTER_TITLE : 'Đăng ký tài khoản',
  ACTION_TITLE: 'Hôm nay bạn làm gì?',
  MONTH: 'THÁNG',
  DAY: 'NGÀY',
  TYPE: [
  	{value: 0, name: 'Ăn uống', color: '#1abc9c', icon: require('../images/food_icon.png')},
  	{value: 1, name: 'Coffee', color: '#34495e', icon: require('../images/coffee_icon.png')},
  	{value: 2, name: 'Thư giãn', color: '#3498db', icon: require('../images/massage_icon.png')},
  	{value: 3, name: 'Đổ xăng', color: '#9b59b6', icon: require('../images/fuel_icon.png')}
  ],
  REGISTER_BTN: 'Đăng ký',
  UPDATE_BTN: 'Cập nhật',
  ALERT_INFO: 'Thông báo',
  ALERT_ERROR: 'Lỗi',
  ALERT_OK: 'Đồng ý',
  ALERT_CANCEL: 'Bỏ qua',
  ALERT_CLOSE: 'Đóng',
  HEADER_TODAY_ALERT: 'Hôm nay bạn đã sử dụng:',
  HEADER_DATE_ALERT: 'Ngày {0} bạn đã sử dụng:',
  CURRENCY: 'VNĐ',
  TYPES_TBL: 'types',
  ACTIONS_TBL: 'actions',
  SETTINGS_TBL: 'settings',
  LOCATIONS_TBL: 'locations',
  USERS_TBL: 'users',
  BACKUP_SUCCESS : 'Đã backup:\n-Loại: {0} dữ liệu.\n-Hoạt động: {1} dữ liệu',
  SYNC_SUCCESS : 'Dữ liệu đã đồng bộ mới nhất.',
  SYNC_COUNT_SUCCESS : 'Đã đồng bộ:\n-Loại: {0} dữ liệu.\n-Hoạt động: {1} dữ liệu.\n-Vị trí: {2} dữ liệu.',
  ACTIONSHEET_SETTING_TITLE: 'Cài đặt',
  BACKUP_FINISH: 'Đã backup tất cả dữ liệu',
  SERVER_ERROR: 'Không thể kết nối tới máy chủ.',
  REGISTER_SUCCESS: 'Đăng ký thành công'
};